[package]
name = "certglass"
version = "0.1.0"
authors = ["Ryan Barry <ryan@nuclearice.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctclient = "0.4.2"
openssl = "0.10.24"
